# House Prices - Advanced Regression Techniques

In this notebook we will be analysing the data and experiment with it.

*To View the full code refer to `kaggle.ipynb` - This notebook was submitted in the competition.*

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Helping functions

In [2]:
obj_mapping = {
  "MSZoning": {
    "A": 0,
    "C": 1,
    "FV": 2,
    "I": 3,
    "RH": 4,
    "RL": 5,
    "RP": 6,
    "RM": 7,
    "C (all)": 8
  },
  "Street": {
    "NA": 0,
    "Grvl": 1,
    "Pave": 2
  },
  "LotShape": {
    "Reg": 0,
    "IR1": 1,
    "IR2": 2,
    "IR3": 3
  },
  "LandContour": {
    "Lvl": 0,
    "Bnk": 0,
    "HLS": 2,
    "Low": 3
  },
  "Utilities": {
    "AllPub": 0,
    "NoSewr": 1,
    "NoSeWa": 2,
    "ELO": 3
  },
  "LotConfig": {
    "Inside": 0,
    "Corner": 1,
    "CulDSac": 2,
    "FR2": 3,
    "FR3": 4
  },
  "LandSlope": {
    "Gtl": 0,
    "Mod": 1,
    "Sev": 2
  },
  "Neighborhood": {
    "Blmngtn": 0,
    "Blueste": 1,
    "BrDale": 2,
    "BrkSide": 3,
    "ClearCr": 4,
    "CollgCr": 5,
    "Crawfor": 6,
    "Edwards": 7,
    "Gilbert": 8,
    "IDOTRR": 9,
    "MeadowV": 10,
    "Mitchel": 11,
    "NAmes": 12,
    "NoRidge": 13,
    "NPkVill": 14,
    "NridgHt": 15,
    "NWAmes": 16,
    "OldTown": 17,
    "SWISU": 18,
    "Sawyer": 19,
    "SawyerW": 20,
    "Somerst": 21,
    "StoneBr": 22,
    "Timber": 23,
    "Veenker": 24
  },
  "Condition1": {
    "Artery": 0,
    "Feedr": 1,
    "Norm": 2,
    "RRNn": 3,
    "RRAn": 4,
    "PosA": 5,
    "PosN": 6,
    "RRNe": 7,
    "RRAe": 8
  },
  "Condition2": {
    "Artery": 0,
    "Feedr": 1,
    "Norm": 2,
    "RRNn": 3,
    "RRAn": 4,
    "PosA": 5,
    "PosN": 6,
    "RRNe": 7,
    "RRAe": 8
  },
  "BldgType": {
    "1Fam": 0,
    "2FmCon": 1,
    "2fmCon": 1,
    "Duplx": 2,
    "Duplex": 2,
    "TwnhsE": 3,
    "TwnhsI": 4,
    "Twnhs": 4
  },
  "HouseStyle": {
    "1Story": 0,
    "1.5Fin": 1,
    "1.5Unf": 2,
    "2Story": 3,
    "2.5Fin": 4,
    "2.5Unf": 5,
    "SFoyer": 6,
    "SLvl": 7
  },
  "RoofStyle": {
    "Flat": 0,
    "Gable": 1,
    "Gambrel": 2,
    "Hip": 3,
    "Mansard": 4,
    "Shed": 5
  },
  "RoofMatl": {
    "ClyTile": 0,
    "CompShg": 1,
    "Membran": 2,
    "Metal": 3,
    "Roll": 4,
    "Tar&Grv": 5,
    "WdShake": 6,
    "WdShngl": 7
  },
  "Exterior1st": {
    "AsbShng": 0,
    "AsphShn": 1,
    "BrkComm": 2,
    "BrkFace": 3,
    "CBlock": 4,
    "CemntBd": 5,
    "HdBoard": 6,
    "ImStucc": 7,
    "MetalSd": 8,
    "Other": 9,
    "Plywood": 10,
    "PreCase": 11,
    "Stone": 12,
    "Stucco": 13,
    "VinylSd": 14,
    "Wd Sdng": 15,
    "WdShing": 16
  },
  "Exterior2nd": {
    "AsbShng": 0,
    "AsphShn": 1,
    "BrkComm": 2,
    "Brk Cmn": 2,
    "BrkFace": 3,
    "CBlock": 4,
    "CemntBd": 5,
    "CmentBd": 5,
    "HdBoard": 6,
    "ImStucc": 7,
    "MetalSd": 8,
    "Other": 9,
    "Plywood": 10,
    "PreCase": 11,
    "Stone": 12,
    "Stucco": 13,
    "VinylSd": 14,
    "Wd Sdng": 15,
    "Wd Shng": 15,
    "WdShing": 16
  },
  "MasVnrType": {
    "NA": 0,
    "None": 0,
    "BrkCmn": 1,
    "BrkFace": 2,
    "CBlock": 3,
    "Stone": 4
  },
  "ExterQual": {
    "Ex": 0,
    "Gd": 1,
    "TA": 2,
    "Fa": 3,
    "Po": 4
  },
  "ExterCond": {
    "Ex": 0,
    "Gd": 1,
    "TA": 2,
    "Fa": 3,
    "Po": 4
  },
  "Foundation": {
    "BrkTil": 0,
    "CBlock": 1,
    "PConc": 2,
    "Slab": 3,
    "Stone": 4,
    "Wood": 5
  },
  "BsmtQual": {
    "NA": 0,
    "Ex": 1,
    "Gd": 2,
    "TA": 3,
    "Fa": 4,
    "Po": 5
  },
  "BsmtCond": {
    "NA": 0,
    "Ex": 1,
    "Gd": 2,
    "TA": 3,
    "Fa": 4,
    "Po": 5
  },
  "BsmtExposure": {
    "NA": 0,
    "No": 0,
    "Gd": 1,
    "Av": 2,
    "Mn": 3
  },
  "BsmtFinType1": {
    "NA": 0,
    "GLQ": 1,
    "ALQ": 2,
    "BLQ": 3,
    "Rec": 4,
    "LwQ": 5,
    "Unf": 6
  },
  "BsmtFinType2": {
    "NA": 0,
    "GLQ": 1,
    "ALQ": 2,
    "BLQ": 3,
    "Rec": 4,
    "LwQ": 5,
    "Unf": 6
  },
  "Heating": {
    "Floor": 0,
    "GasA": 1,
    "GasW": 2,
    "Grav": 3,
    "OthW": 4,
    "Wall": 5
  },
  "HeatingQC": {
    "Ex": 0,
    "Gd": 1,
    "TA": 2,
    "Fa": 3,
    "Po": 4
  },
  "CentralAir": {
    "N": 0,
    "Y": 1
  },
  "Electrical": {
    "NA": 0,
    "SBrkr": 1,
    "FuseA": 2,
    "FuseF": 3,
    "FuseP": 4,
    "Mix": 5
  },
  "KitchenQual": {
    "Ex": 0,
    "Gd": 1,
    "TA": 2,
    "Fa": 3,
    "Po": 4
  },
  "Functional": {
    "Typ": 0,
    "Min1": 1,
    "Min2": 2,
    "Mod": 3,
    "Maj1": 4,
    "Maj2": 5,
    "Sev": 6,
    "Sal": 8
  },
  "FireplaceQu": {
    "NA": 0,
    "Ex": 1,
    "Gd": 2,
    "TA": 3,
    "Fa": 4,
    "Po": 5
  },
  "GarageType": {
    "2Types": 1,
    "Attchd": 2,
    "Basment": 3,
    "BuiltIn": 4,
    "CarPort": 5,
    "Detchd": 6
  },
  "GarageFinish": {
    "NA": 0,
    "Fin": 1,
    "RFn": 2,
    "Unf": 3
  },
  "GarageQual": {
    "NA": 0,
    "Ex": 1,
    "Gd": 2,
    "TA": 3,
    "Fa": 4,
    "Po": 5
  },
  "GarageCond": {
    "NA": 0,
    "Ex": 1,
    "Gd": 2,
    "TA": 3,
    "Fa": 4,
    "Po": 5
  },
  "PavedDrive": {
    "N": 0,
    "P": 1,
    "Y": 2
  },
  "PoolQC": {
    "NA": 0,
    "Ex": 1,
    "Gd": 2,
    "TA": 3,
    "Fa": 4,
    "Po": 5
  },
  "Fence": {
    "NA": 0,
    "GdPrv": 1,
    "MnPrv": 2,
    "GdWo": 3,
    "MnWw": 4
  },
  "MiscFeature": {
    "NA": 0,
    "Elev": 1,
    "Gar2": 2,
    "Othr": 3,
    "Shed": 4,
    "TenC": 5
  },
  "SaleType": {
    "WD": 0,
    "CWD": 1,
    "VWD": 2,
    "New": 3,
    "COD": 4,
    "Con": 5,
    "ConLw": 6,
    "ConLI": 7,
    "ConLD": 8,
    "Oth": 9
  },
  "SaleCondition": {
    "Normal": 0,
    "Abnorml": 1,
    "AdjLand": 2,
    "Alloca": 3,
    "Family": 4,
    "Partial": 5
  },
  "Alley": {
    "NA": 0,
    "Grvl": 1,
    "Pave": 2
  }
}

In [3]:
def pd_to_csv(data, file_path):
    with open(file_path, "w") as f:
        f.write(data.to_csv())

    return 'DONE'

def transform_csv(df, save_path):
    import json

    # Replacing
    for column, mapping in obj_mapping.items():
        df[column].replace(mapping, inplace=True)
    
    # Replacing all empty values with 0
    df.fillna(0, inplace=True)

    # Save the data
    with open(save_path, "w") as f:
        f.write(df.to_csv())

# Loading the Data

In [4]:
train_dataset_path = "/kaggle/input/house-prices-advanced-regression-techniques/train.csv"
test_dataset_path = "/kaggle/input/house-prices-advanced-regression-techniques/test.csv"

In [5]:
train_dataset = pd.read_csv(train_dataset_path)

test_dataset = pd.read_csv(test_dataset_path)

# Analysing the Data

In [6]:
train_dataset.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
test_dataset.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

## Missing Values

In [8]:
# Saving Missing Values in train_dataset
pd_to_csv(train_dataset.isna().sum(), "/kaggle/working/train_missing_values.csv")

# Saving Missing Values in train_dataset
pd_to_csv(test_dataset.isna().sum(), "/kaggle/working/test_missing_values.csv")

'DONE'

In [9]:
# Viewing the Missing Values
train_missing_values = pd.read_csv("/kaggle/working/train_missing_values.csv")

train_missing_values

       Unnamed: 0    0
0              Id    0
1      MSSubClass    0
2        MSZoning    0
3     LotFrontage  259
4         LotArea    0
..            ...  ...
76         MoSold    0
77         YrSold    0
78       SaleType    0
79  SaleCondition    0
80      SalePrice    0

[81 rows x 2 columns]

## DataTypes

In [10]:
train_dataset.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

*Here, we can see that not all the datatypes are in integer or float, they are in object (i.e. String). Which means we need to convert them to number in order to convert them to tensors.*

## Duplicated Values

In [11]:
print("Training Dataset Duplicated Values")
print(train_dataset.duplicated().sum())

print("\n----------------\n")

print("Test Dataset Duplicated Values")
print(test_dataset.duplicated().sum())

Training Dataset Duplicated Values
0

----------------

Test Dataset Duplicated Values
0

**NOTE**: After viewing the data and `data_description`, I came to understand that no data is missing, everthing is given and we just need to convert them to desired output.

# Pre-Processing Data

This would involve transforming the data which would be best for our ML.

To know how it was achieved in detail, please refer to [Transform Data Guide](https://github.com/adityajideveloper/kaggle-competition/house-prices/transform_data.md)

In [13]:
transform_csv(train_dataset, "/kaggle/working/train.csv")
transform_csv(test_dataset, "/kaggle/working/test.csv")

## Getting Data Ready

In [14]:
df = pd.read_csv("/kaggle/working/train.csv")
df_test = pd.read_csv("/kaggle/working/test.csv")

df.head(5)

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,1,60,5,65.0,8450,2,0.0,0,0,...,0,0.0,0.0,0.0,0,2,2008,0,0,208500
1,1,2,20,5,80.0,9600,2,0.0,0,0,...,0,0.0,0.0,0.0,0,5,2007,0,0,181500
2,2,3,60,5,68.0,11250,2,0.0,1,0,...,0,0.0,0.0,0.0,0,9,2008,0,0,223500
3,3,4,70,5,60.0,9550,2,0.0,1,0,...,0,0.0,0.0,0.0,0,2,2006,0,1,140000
4,4,5,60,5,84.0,14260,2,0.0,1,0,...,0,0.0,0.0,0.0,0,12,2008,0,0,250000

In [15]:
# Removing ID
df = df.drop(df.columns[0], axis=1)
df = df.drop("Id", axis=1)

In [16]:
# Splitting the Data

from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [17]:
# Further splitting data in X and y
X_train = train_set.drop("SalePrice", axis=1).to_numpy()
y_train = train_set['SalePrice'].to_numpy()

X_test = test_set.drop("SalePrice", axis=1).to_numpy()
y_test = test_set['SalePrice'].to_numpy()

In [18]:
# This function was written as described in Competition Evaluation Overview
# https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview/evaluation

def acc_fn(y_pred, y_true):
    absoulute_error = np.log(y_true) - np.log(y_pred)
    square_error = np.square(absoulute_error)
    MSE = np.mean(square_error)
    RMSE = np.sqrt(MSE)

    return RMSE

# Creating Decision Tree

In [19]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(criterion="squared_error", random_state=42, learning_rate=0.0001, loss="squared_error", n_estimators=100_000)

# Training the Model

In [ ]:
model.fit(X_train, y_train)

In [ ]:
print(f"Train Score -> {acc_fn(model.predict(X_train), y_train)}")
print(f"Test Score -> {acc_fn(model.predict(X_test), y_test)}")

# Submission

In [ ]:
test_data = df_test.drop(df_test.columns[0], axis=1).drop("Id", axis=1).to_numpy()
test_ids = df_test["Id"].to_numpy()

print(f"Total Ids -> {len(test_ids)}")

# Opening CSV file
import csv

with open("/kaggle/working/submission.csv", "w") as f:
    writer = csv.writer(f)
    
    writer.writerow(["Id", "SalePrice"])
    
    # Looping through the data
    for i, sale_price in enumerate(model.predict(test_data)):
        writer.writerow([test_ids[i], sale_price])